get:
  tags:
    - ProductAPI
  summary: Index
  description: Get all the products from the products table
  operationId: ProductAPIIndex
  security: []
    # - api_key: []
    # - basic_auth: []
  responses:
    '200':
      description: OK
      content:
        application/json:
          schema:
            $ref: ../components/schemas/GetProducts.yaml

    '400':
      description: Unauthorized
  requestBody:
    content:
      application/json:
        schema:
          type: string
          example: null
    description: payload
    required: true
  x-codeSamples:
    - lang: PHP
      source:
        $ref: ../code_samples/PHP/echo/getproducts.php

# post:
#   tags:
#     - BasketItemAPI
#   summary: Store
#   description: Store the item in the basket and increment the addedCount field in the item_stats table
#   operationId: BasketItemAPIStore
#   security: []
#     # - api_key: []
#     # - basic_auth: []
#   responses:
#     '200':
#       description: OK
#       content:
#         application/json:
#           schema:
#             $ref: ../components/schemas/StoreBasketItems.yaml
#     '400':
#       description: Unauthorized
#   requestBody:
#     content:
#       application/json:
#         schema:
#           type: string
#           example: null
#     description:  payload
#     required: true
#   x-codeSamples:
#     - lang: PHP
#       source:
#         $ref: ../code_samples/PHP/echo/postbasket.php
# delete:
#   tags:
#     - BasketItemAPI
#   summary: Delete
#   description: Delete the item in the basket and increment the purchasedCount or the removedCount field in the item_stats table depending the stat_type.
#   operationId: BasketItemAPIDelete
#   security: []
#     # - api_key: []
#     # - basic_auth: []
#   responses:
#     '200':
#       description: OK
#       content:
#         application/json:
#           schema:
#             $ref: ../components/schemas/DeleteBasketItems.yaml
#     '400':
#       description: Unauthorized
#   requestBody:
#     content:
#       application/json:
#         schema:
#           type: array
#           example: ['stat_type': 'checkout']
#     description:  payload
#     required: true
#   x-codeSamples:
#     - lang: PHP
#       source:
#         $ref: ../code_samples/PHP/echo/deletebasket.php
