openapi: 3.1.0
info:
  version: ''
  title: Shopping Hive
  contact:
    email: mghossain.42@gmail.com
  description:
    $ref: ./info-description.md
tags:
  - name: APIs
    description: This solution contains three APIs
  - name: BasketItemAPI
    description: Responsible for showing, storing, and deleting the basket item, as well as handling the sales data by logging the Item Stats.
  - name: ProductAPI
    description: Responsible for showing all of the Products.
  - name: ItemStatAPI
    description: Responsible for showing the sales stats.
servers:
  - url: 'https://localhost.com/api'
paths:
  /basket:
    $ref: paths/echo.yaml
  /product:
    $ref: paths/product.yaml
  /stats:
    $ref: paths/stats.yaml

components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://example.com/api/oauth/dialog'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic